name: Opsworks deploy
description: Opsworks deploy
author: aki77
inputs:
  stackId:
    description: "Stack id"
    required: false
  appId:
    description: "App id"
    required: false
  region:
    description: "Region"
    required: false
    default: "ap-northeast-1"
outputs:
  status:
    description: Status
runs:
  using: "node12"
  main: "dist/index.js"
